### ISSUE TITLE
SMTP Is Disconnected

### ISSUE THREAD

**Issue by alexmacniven** [sunshinetechnology/mail#2]
```
Traceback (most recent call last):
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.6\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.6\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Data-Drive\Source\serhs\app\__main__.py", line 5, in <module>
    cli.cli()
  File "C:\Data-Drive\Source\serhs\venv\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Data-Drive\Source\serhs\venv\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Data-Drive\Source\serhs\venv\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Data-Drive\Source\serhs\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Data-Drive\Source\serhs\venv\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Data-Drive\Source\serhs\app\cli.py", line 66, in fetch_command
    runner()
  File "C:\Data-Drive\Source\serhs\app\cli.py", line 61, in runner
    mailer.send(server)
  File "C:\Data-Drive\Source\serhs\venv\lib\site-packages\mail\core.py", line 42, in send
    smtp.ehlo()
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.6\lib\smtplib.py", line 446, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.6\lib\smtplib.py", line 373, in putcmd
    self.send(str)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.6\lib\smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
```

**Comment by alexmacniven** [comment]
This is fine. I forgot to load the variables into the environment.
